[versions]
agp = "8.13.2"
concurrentFutures = "1.2.0"
glide = "4.16.0"
guava = "33.3.1-android"
kotlin = "1.9.24"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
kotlinxCoroutinesGuava = "1.6.0"
material = "1.10.0"
constraintlayout = "2.1.4"
lifecycleLivedataKtx = "2.6.1"
lifecycleViewmodelKtx = "2.6.1"
media3 = "1.5.1"
navigationFragmentKtx = "2.6.0"
navigationUiKtx = "2.6.0"
cameraLifecycle = "1.4.1"
cameraVideo = "1.4.1"
cameraView = "1.4.1"
cameraCamera2 = "1.4.1"

javacv = "1.5.11"
javacpp = "1.5.10"
javacvOpenblas = "0.3.28-1.5.11"
javacvFfmpeg = "7.1-1.5.11"
javacvOpencv = "4.10.0-1.5.11"
javacvVideoinput = "0.200-1.5.9"

[libraries]
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrentFutures" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
androidx-media3-common-ktx = { module = "androidx.media3:media3-common-ktx", version.ref = "media3" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinxCoroutinesGuava" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
androidx-camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "cameraVideo" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraCamera2" }


javacv = { group = "org.bytedeco", name = "javacv", version.ref = "javacv" }
javacpp = { group = "org.bytedeco", name = "javacpp", version.ref = "javacpp" }
openblas = { group = "org.bytedeco", name = "openblas", version.ref = "javacvOpenblas" }
ffmpeg = { group = "org.bytedeco", name = "ffmpeg", version.ref = "javacvFfmpeg" }
opencv = { group = "org.bytedeco", name = "opencv", version.ref = "javacvOpencv" }
videoinput = { group = "org.bytedeco", name = "videoinput", version.ref = "javacvVideoinput" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

